name: Release

on:
  push:
    branches:
      - 'main'

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 🎉 checkout
        uses: actions/checkout@v3

      - name: 🎉 node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'

      - name: 🎉 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: 🎉 cache
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: 🎉 install
        run: pnpm i

      - name: 🎉 test
        run: pnpm -r test --if-present

      - name: 🎉 build
        run: pnpm -r build --if-present

      - name: 🎉 info
        run: npm info @pungfe/prettier-config

      - name: 🎉 changeset
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: update version'
          publish: pnpm run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUNGFE }}
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUNGFE }}
